version: '3.8'

services:
  # n8n - Workflow Automation
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=n8n_vgnc_2024
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Europe/Berlin
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - vgnc_network

  # Homepage - Dashboard
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - "8080:3000"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - vgnc_network

  # Netdata - System Monitoring
  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    restart: unless-stopped
    ports:
      - "19999:19999"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - netdata_config:/etc/netdata
      - netdata_cache:/var/cache/netdata
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    networks:
      - vgnc_network

  # Portainer - Docker Management
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - vgnc_network

  # Telegram Bot (Node.js)
  telegram-bot:
    build: ./telegram-bot
    container_name: telegram-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
    volumes:
      - telegram_bot_data:/app/data
    networks:
      - vgnc_network

  # Minecraft Server
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      - EULA=TRUE
      - MEMORY=2G
      - TYPE=PAPER
      - VERSION=LATEST
      - DIFFICULTY=normal
      - SPAWN_PROTECTION=16
      - PVP=true
      - MOTD=VGNC Minecraft Server
      - ENABLE_RCON=true
      - RCON_PASSWORD=minecraft_vgnc_2024
      - RCON_PORT=25575
    volumes:
      - minecraft_data:/data
    networks:
      - vgnc_network

  # Nextcloud
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud_vgnc_2024
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.vgnc.org
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloud_vgnc_2024
    volumes:
      - nextcloud_data:/var/www/html
      - nextcloud_apps:/var/www/html/custom_apps
      - nextcloud_config:/var/www/html/config
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - vgnc_network

  # Nextcloud Database (MariaDB)
  nextcloud-db:
    image: mariadb:10.6
    container_name: nextcloud-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud_root_2024
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud_vgnc_2024
    volumes:
      - nextcloud_db_data:/var/lib/mysql
    networks:
      - vgnc_network

  # Nextcloud Redis Cache
  nextcloud-redis:
    image: redis:7-alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    volumes:
      - nextcloud_redis_data:/data
    networks:
      - vgnc_network

volumes:
  n8n_data:
  netdata_config:
  netdata_cache:
  portainer_data:
  telegram_bot_data:
  minecraft_data:
  nextcloud_data:
  nextcloud_apps:
  nextcloud_config:
  nextcloud_db_data:
  nextcloud_redis_data:

networks:
  vgnc_network:
    driver: bridge 